### ISSUE TITLE
New source

### ISSUE THREAD

**Issue by shahabvbnet** [Alephgsm/SharpOdinClient#6]
Hello. Please create an example with vbnet. I could not convert the project to vbnet

**Comment by Alephgsm** [comment]
what problem you have for using in vb.net?

**Comment by shahabvbnet** [comment]
I have a problem with the line of code to display the logs in the richtextbox.

**Comment by Alephgsm** [comment]
Check this issue
https://github.com/Alephgsm/SharpOdinClient/issues/4

**Comment by shahabvbnet** [comment]
I wrote this but it still doesn't show
